spring:
    application:
      name: JPA Inheritance - Mapped Supperclass
    # Datasource configuration
    datasource:
        url: jdbc:mysql://localhost/inheritance?useUnicode=true&characterEncoding=utf8&useSSL=false
        name: MySQL Connection
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
        # JPA configuration
        jpa:
            database-platform: org.hibernate.dialect.MySQLInnoDBDialect
            database: MYSQL
            show_sql: false
            properties:
                hibernate.cache.use_second_level_cache: false
                hibernate.cache.use_query_cache: false
                hibernate.generate_statistics: true
    # liquibase configuration
    liquibase:
        change-log: classpath:liquibase/db-master.xml